### ISSUE TITLE
Inconsistent API

### ISSUE THREAD

**Issue by lyrixx** [jolicode/castor#108]
## ATM, we have:

```php
function(SymfonyStyle $io)
{
    $io->ask();
    fs()->mkdir();
}
```

It's not consistent: 

* $io is passed via the function argument
* $fs is got via a function

For the record, here is list of param supported via the DI
* Context
* SymfonyStyle
* Application
* Command
* InputInterface
* OutputInterface

[ref](https://github.com/jolicode/castor/blob/main/src/Console/Command/TaskCommand.php#L25-L30)

### Everything via DI

```php
function(SymfonyStyle $io, Filesystem $fs)
{
    $io->ask();
    $fs->mkdir();
}
```

### Cons

* You have to know each type + import a NS + it's long
* It'll not work well with the finder: there is a state in it, so you cannot use it twice (or you have to clone it)
* It does not play well when command chaining 

### Pros

* It's cleaner

## Everything as a function

```php
function()
{
    io()->ask();
    fs()->mkdir();
}
```

Pros & cons are the opposite of "Everything via DI"

---

I would vote for function, but I'm not 100% sure!

**Comment by damienalexandre** [comment]
I vote for functions, it's easier to use IMO.
