### ISSUE TITLE
Add a spinner

### ISSUE THREAD

**Issue by welcoMattic** [jolicode/castor#149]
Using `parallel()` make the output empty until the first task is done. We could provide a spinner to inform user the tasks are running.

**Comment by lyrixx** [comment]
It would be awesome to fix https://github.com/symfony/symfony/issues/35012

**Comment by lyrixx** [comment]
It's already in Symfony https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Console/Helper/ProgressIndicator.php
