### ISSUE TITLE
Conditional `import`

### ISSUE THREAD

**Issue by Korbeil** [jolicode/castor#155]
Hey :wave: 
Today we can't conditionally use `import` method because the context isn't loaded on runtime.

For example:
```php
if (variable('VARNISH_URL')) {
  import(__DIR__ . '/scripts/varnish.php');
}
```
Won't work because we have a default empty Context on runtime and the real context is only loaded later on.

I would like to do something like that:
```php
import(__DIR__ . '/scripts/varnish.php', fn(Context $c) => $c->offsetExists('VARNISH_URL'));
```
So Castor import that file (or directory) only if the given callback returns `true` (callback should be optional and if none provided it will always import the file/directory).

**Comment by joelwurtz** [comment]
It won't work when the default context is loaded with an import (you will have a bad context in this case)

Conditional import is a big source of problems IMO, if your use case is to have a command that is only available on some context then it would be better to add or update an existing attribute to handle this behavior (so we can link a command to a specific context)
