### ISSUE TITLE
Add possibility to keep the directory of imported castor file

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#160]
Hello all !

I would like to know if it is possible to add an option to import for indicating this import to keep the directory where is located imported castor.php as currentDirectory.

Example

I have a project structure that have : 
```
webdev/
├─ projects/
│  ├─ A/
│  │  ├─ docker-compose.yml
│  │  ├─ castor.php
│  ├─ B/
│  │  ├─ docker-compose.yml
│  │  ├─ castor.php
├─ docker-compose.yml
├─ castor.php
```

castor.php at `~/webdev/castor.php` as a PWD of `~/webdev` and all import too

I'm in `~/webdev` folder, I call the `castor start` for starting docker-compose.yml at `~/webdev/docker-compose.yml` that OK, but in this same start, I want to question user if I want to start the project A located in `~/webdev/projects/A` if user confirm, I call the start task from the castor file located in `~/webdev/projects/A`, but this one as PWD of `~/webdev`

A suggest would be to keep the PWD of imported like that if possible
`import(__DIR__ . '/projects/A/castor.php', keepOriginalDirectory: true);`

With that all functions importe from `~/webdev/projects/A/castor.php` will have `~/webdev/projects/A` as currentDirectory

As of today for make this possible, i make a "default context" that have currentDirectory to `__DIR__`, that is the right way ?

![image](https://github.com/jolicode/castor/assets/72203064/a5c689cb-8e4c-4929-834a-547dbc80c51b)

**Comment by lyrixx** [comment]
Hello,

Thanks for this very detailed issue.

I understand your feature, and It looks like it's legit to add this option. However, I would call this option `followCurrentDirectory` or `updateCurrentDirectory`. Because `keepOriginalDirectory` is really misleading. 

But I think it'll be hard to implement :/ Someone should give it a try! maybe it'll be easy.

**Comment by TheoD02** [comment]
> Member

Hey, thanks for the response :)

Yes, the name wasn't the most coherent! ^^

I can see that the implementation is likely to be complex :/ `run` function is independent of the import, which does not allow access to the DIR of the imported file.

For the moment, I've managed to play around with a different approach, where I declare all my contexts in a contexts.php file, then import this file and run('xxx', located_context());

But if I change the location of this one, it'll probably break.

Your approach is more understandable 🥇

**Comment by joelwurtz** [comment]
I don't think this is easily feasible, and will introduce a lot of headcache when trying to make it right, for now like @lyrixx said the only option is to run the command with path: __DIR__

You can also use the `with` function to register all your runs under a specific directory, but overall command that are sensible to directories should have it fixed (with __DIR__ or other methods), also i don't like that the behavior of a method need a specific configuration (using a parameter) it add a responsibility on the code using this code which is not normal

I'm going to close this, but if someone think of a better api feel free to reopen and expose your pov
