### ISSUE TITLE
Castor completion installation

### ISSUE THREAD

**Issue by moufmouf** [jolicode/castor#174]
Hey Jolicode!

Just testing Castor. Here is a small feedback.

The documentation states you can install autocompletion by running:

```
castor completion | sudo tee /etc/bash_completion.d/castor
```
 (here: https://github.com/jolicode/castor/blob/main/doc/01-installation.md#autocomplete)

The problem is that unless you have a `castor.php` file in the current directory, `castor completion` will fail.

And since you run this command just after installing Castor, it is unlikely that there is a `castor.php` file in the directory where you are running 

```
castor completion | sudo tee /etc/bash_completion.d/castor
```

See ya!

**Comment by pyrech** [comment]
Hi @moufmouf. Thanks for your issue. For your information, I just implemented a fix in #175 :wink:
