### ISSUE TITLE
Latest release conflicts with old versions of Docker Compose

### ISSUE THREAD

**Issue by HedicGuibert** [jolicode/castor#177]
Using the latest Castor release (`0.8.0` at the time of writing) and an older Docker Compose version (`2.3.3`), I encountered the following error while running `castor start` for the first time :

> invalid service "frontend". Must specify either image or build

Which happened when it ran 

> The command "'docker' 'compose' '-p' 'cettefamille-form' '-f' '/home/hedic/Dev/JoliCode/cettefamille-form/infrastructure/docker/docker-compose.yml' '-f' '/home/hedic/Dev/JoliCode/cettefamille-form/infrastructure/docker/docker-compose.worker.yml' 'up' '--remove-orphans' '--detach' '--no-build'" failed.

I could fix the issue by upgrading Docker Compose to 2.20.3.

It probably would be a good idea to inform users that Castor is incompatible with older versions of Docker Compose ? I don't know up to which version the issue exists, hence I'm not opening a PR to update the readme

**Comment by pyrech** [comment]
Closing as this issue is related to jolicode/docker-starter :slightly_smiling_face:
