### ISSUE TITLE
What about using class for declaring some Task ?

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#184]
Hey there!

I'd like to gather your thoughts on adopting a class-based approach. By the "class approach," I mean structuring our code like this:

```php
symfony()->loco()->pull();
```

This approach is currently possible with version 0.8 of Castor. However, when it comes to exposing task `symfony:loco:pull` of methods in objects, it's not currently feasible.

And for now for exposing this i need to "repeat" it like this : 
```php
#[AsTask(name: 'pull', namespace: 'loco', description: 'Download translations from Loco.')]
function locoPull(): Process
{
    return symfony()->loco()->pull();
}
```

## Proposed Approach

Let's consider the following implementation:

**Symfony.php**

```php
#[AsTaskClass(namespace: 'symfony')]
class Symfony
{
    private string $cmd = 'php bin/console';

    public function console(
        string $command,
        array $args = [],
        array $options = []
    ): Process {
        $cmd = "{$this->cmd} {$command}";

        // Add some logic for options and args

        return docker()->exec($cmd, interactive: true, tty: true);
    }

    public function loco(): Loco
    {
        return new Loco();
    }
}

function symfony(): Symfony
{
    return new Symfony();
}
```

**Loco.php**

```php
#[AsTaskClass(namespace: 'symfony:loco')]
class Loco
{
    public function __construct() // Not usable if we use static
    {
        $context = context();
        if (!is_dir($context->currentDirectory . '/vendor/symfony/loco-translation-provider')) {
            io()->error("Loco translation provider is not installed in {$context->data['name']}.");
            exit(1);
        }
    }

    #[AsTask(description: 'Pull loco translation')]
    public static function pull(string $format = 'json'): \Symfony\Component\Process\Process
    {
        io()->section('Pulling translations from Loco');
        return symfony()->console("translation:pull --format={$format}");
    }

    #[AsTask(description: 'Push loco translation')]
    public static function push(): \Symfony\Component\Process\Process
    {
        io()->section('Pushing translations to Loco');
        return symfony()->console('translation:push');
    }
}
```

This will provide the Castor commands in the same way as the current flow:

![image](https://github.com/jolicode/castor/assets/72203064/1d2caba6-1b91-4d1c-8426-9a753cac260b)

As of today, it is not possible to use `AsTask` in objects because `doFindFunctions` searches only for functions in `get_defined_functions()` of the user.

One reason I used this approach is to allow sending custom context and params like this if needed, and in case none are sent, we are using the default context:

```php
symfony(ctx: my_project(), tenant: 'MY_TENANT')->console('create:user --email xxx@mail.com');
```

I've started some things that work fine. Please take a look and review here: [GitHub Link](https://github.com/TheoD02/castor/commit/e677e79eb26ce5084c6d20d9f2316df185c6c61d)

If the approach is appreciated, I'm happy to open a new PR! 😄

Actually, I catch all `public static methods` of the class. Using non-static methods is doable, but I didn't know at the moment what the best approach is. Let me know what you think.
Non-static can be useful, like in Loco::__construct() where i check if library is available before any methods call

## Why This Approach?

You might be wondering why I'm suggesting this approach instead of using namespaces like `\symfony\loco\pull();`. I believe that the current way, utilizing class methods, offers better readability and maintainability for our codebase.

Feel free to share your thoughts and concerns regarding this proposal!

**Comment by lyrixx** [comment]
Hello,

Thanks for your issue. 

But I don't think it matches our vision. We wanted to build something very simple, function oriented. It works very well for use and we are happy with it.

So I'm against this proposal. Sorry!

But let's wait for other feedback before closing this issue.

**Comment by pyrech** [comment]
I agree with @lyrixx here. Castor was build on purpose to provide tasks as simple-to-write-functions so I vote against too. But thank you for your suggestion :pray:

**Comment by lyrixx** [comment]
Thanks again for the proposal. We discussed about it internally, and we decided to not accept it. Sorry! But you are welcome to open new PR / issue if you want 💛
