### ISSUE TITLE
Testability and Dry-run

### ISSUE THREAD

**Issue by geek-merlin** [jolicode/castor#194]
Great you created this, \me and i guess quite some others suffer from similar pain.
There are two blockers for me though:
- a `--dry-run` option
- and a way to test my tasks

I'm putting these into one issue becuse these are quite related:
- For some tasks, i can simply do a dry-run and compare the output
- For other tasks, i additionally have to mock some sub-tasks (like at least remote calls)

Is this missing or did i miss something?

**Comment by lyrixx** [comment]
Hello,

Thanks for your interest in castor

> a --dry-run option

You can add `--dry-run` option, by adding a `bool $dryRun = false` argument in your task.

In the README, there is an example with a `--force` option: https://github.com/jolicode/castor#usage

Then, you can do what you want according with this option :

> and a way to test my tasks

All examples are tested, you can take inspiration from them: https://github.com/jolicode/castor/tree/main/tests/Examples

**Comment by geek-merlin** [comment]
OK, I groked that and get where you're coming from.
Yes, we can close this, and i'll implement some projects and follow up when i have more specific issues.

Thanks a lot for the quick answer, and the whole project. Appreciated a lot!
