### ISSUE TITLE
Output is cut off at some places

### ISSUE THREAD

**Issue by jacquesbh** [jolicode/castor#195]
Hi!

When I use the `capture()` function with a command that renders a lot of output (like a big JSON), I realize that the output is cut off at some points.

Example with a simple JSON (understand that a big one is returned by the command):

```json
{
  "foo": "Yo",
  "bar": "Yoo"
}
```

I often get something like this:

```json
{
  "foo": "Yo",
  "bar
"Yoo"
}
```

Or like this:
```json
{
  "foo": "Yo"
"bar": "Yoo"
}
```

I use the `clever create` command to create clever cloud instances with the `--format json` to get a full json of the newly created app, this json is quite huge and I get a valid response like one on 30 calls… I've tested the response of the binary itself, alone, and I always have a valid JSON.

Thank you!

**Comment by lyrixx** [comment]
@jacquesbh thanks for the report! Indeed there is an issue in castor. It looks like it come from the SectionOutput.

I made a reprocuder : 

```php

<?php

namespace reproducer;

use Castor\Attribute\AsTask;
use Symfony\Component\Process\Process;

use function Castor\capture;
use function Castor\run;

#[AsTask()]
function issue166(): void
{
    if (!is_file('/tmp/failure')) {
        file_put_contents(
            '/tmp/failure',
            json_encode(
                json_decode(
                    file_get_contents('https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json'),
                    true
                ),
                JSON_PRETTY_PRINT
            )
        );
    }

    // OK with raw symfony
    // $p = new Process(['cat', '/tmp/failure']);
    // $p->mustRun();

    $p = run(['cat', '/tmp/failure'], quiet: true);
    echo $p->getOutput();
}
```

---

@joelwurtz Can you have a look at it? Thanks

**Comment by jacquesbh** [comment]
Hi guys! @lyrixx and @joelwurtz 

Did you have some time to look at it? ❤️

**Comment by mmenozzi** [comment]
I have a similar issue... I use castor to run [doctl](https://docs.digitalocean.com/reference/doctl/) as follows:

```php
capture('doctl compute image list --format "Name,ID"')
```

Most of the time I have the complete output but sometimes I have a truncated output.
The same happens with:

```php
run('doctl compute image list --format "Name,ID"', quiet: true)->getOutput()
```

**Comment by lyrixx** [comment]
@joelwurtz FYI, I'm gonna revert your work done on the section, since it does not work as expected. Sorry

**Comment by lyrixx** [comment]
Hello, sorry for the delay.
can you try #251 ? thanks

**Comment by mmenozzi** [comment]
Thank you guys!
