### ISSUE TITLE
One liner install doesn't work on Linux

### ISSUE THREAD

**Issue by tlenclos** [jolicode/castor#200]
I tried to install Castor with the one liner in the documentation (also I think it could before the "Usage" section) and it failed without errors:

```
>curl "https://github.com/jolicode/castor/releases/latest/download/castor.linux-amd64.phar" -Lso $HOME/.local/bin/castor && chmod u+x $HOME/.local/bin/castor
>castor
Command 'castor' not found, did you mean:
  command 'cantor' from snap cantor (23.08.3)
  command 'cantor' from deb cantor (4:21.12.3-0ubuntu1)
See 'snap info <snapname>' for additional versions.
```

I got a classic Ubuntu 22 installation. Should I be using the `$HOME/.local/bin` as it doesn't exist ?
I see that [Robo](https://robo.li/) is using this one liner that worked with the `/usr/bin` directory:

```
wget https://robo.li/robo.phar && chmod +x robo.phar && sudo mv robo.phar /usr/bin/robo
```

**Comment by lyrixx** [comment]
1. Should we recommande to instrall castor in `/usr/local/bin/castor`? It required sudo, but this folder always exist
2. Should we write a very simple installer.php to handler case when a directory does not exist?
3. Should we handle failure generically ? 
    ```bash
    curl "https://github.com/jolicode/castor/releases/latest/download/castor.linux-amd64.phar" -Lso $HOME/.local/bin/castor && chmod u+x $HOME/.local/bin/castor || (echo "Could not install castor. Is the target directory writeable?" && (exit 1))
    ```
5. should we do something else?
