### ISSUE TITLE
Add a helper to run a command if some files changed since last execution

### ISSUE THREAD

**Issue by jeckel** [jolicode/castor#202]
In some project with docker, I have this recipes in my `Makefile` :

```makefile
# Rebuild docker images if changes detected
var/.docker-build: docker-compose.yml .env $(shell find .docker -type f)
	@docker-compose build
	@mkdir -p var
	@touch var/.docker-build
	
up: var/.docker-build
	@docker-compose up
```

Each time I launch `make up` it checks if the file `var/.docker-build` is more recent that any files required to build my docker images (`docker-compose.yml`, `.env`, any files in `.docker` directory). If not, then images are rebuilt and time of `var/.docker-build` file is updated.

This is the only recipe in my `Makefile` I can't replace with `castor` for now.

We can maybe think of some helper like this:

```php

use function Castor\is_updated;
use function Castor\run;

if (is_updated(['docker-compose.yml', '.env', '.docker/*']) {
    run("docker-compose build");
}
```

**Bonus:** this will be more readable than the `Makefile` version.

**Comment by TheoD02** [comment]
Hi 😄 

See `fingerprints` this should do what you expect (https://github.com/jolicode/castor/blob/main/doc/14-fingerprint.md)

**Comment by jeckel** [comment]
My bad, I didn't see this usage of fingerprints.

Thanks a lot
