### ISSUE TITLE
Need for a `wait_for` helper

### ISSUE THREAD

**Issue by jeckel** [jolicode/castor#207]
Hi there,

When I'm working with docker container for example, I often need to wait that a container is ready (healthy) before processing any other action.

We can think of a helper like this :

```php
/**
 * @param callable(): bool $callback
 * @param int $timeout Maximum number of seconds to wait before throwing a TimeoutException
 * @param int $interval Interval in second between calls to the $callback function
 * @throw TimeoutException
 */
function wait_for(callable $callback, int $timeout = 10, int $interval = 1): void;
```

If you think it's a good feature, I can try a PR

**Comment by jeckel** [comment]
Or maybe it can return a boolean instead of throwing an Exception ?

**Comment by TheoD02** [comment]
Hello, 

That could be cool ! I use this pattern too for waiting docker container, or for waiting HTTP service on certain port (+ payload if necessary) to be accessible.

Make this type of helper (docker, network…) as shared castor files in a specific repo when [import functions from remote](https://github.com/jolicode/castor/pull/136) will be OK and merged should be cool :)

**Comment by lyrixx** [comment]
Good idea
