### ISSUE TITLE
[Documentation] Install Castor via composer global

### ISSUE THREAD

**Issue by thedomeffm** [jolicode/castor#210]
I wanted to install castor via composer (globally).

The [documentation](https://github.com/jolicode/castor/blob/main/doc/01-installation.md) said the package will be available from here:
> Then make sure that the Composer global bin directory is in your PATH:
`export PATH="$HOME/.composer/vendor/bin:$PATH"`

But it did not work.
I saw the stackoverflow article to see the configured composer global path via: `composer config --list --global` that resulted in:
```bash
// other lines...
[home] /home/<user>/.config/composer
```

So at least in my setup I needed to `export PATH="$HOME/.config/composer/vendor/bin:$PATH"`.

I am not a composer expert, just a "user" so I am not sure if this is just a Linux thing, or did I configured it in the past to be in this path... I don't know. 
At least I wanted to share this with you guys, so probably when this is the "new composer standard" we could change it in the docs.

If the strange configuration is just my user error, please bear with me - I'm sorry.

**Comment by pyrech** [comment]
Hello @thedomeffm, thanks for your issue 🙂

You're right, the location of the global path is not that simple. Composer's [documentation](https://getcomposer.org/doc/03-cli.md#composer-home) states that:

> By default, it points to C:\Users\<user>\AppData\Roaming\Composer on Windows and /Users/<user>/.composer on macOS. On *nix systems that follow the XDG Base Directory Specifications, it points to $XDG_CONFIG_HOME/composer. On other *nix systems, it points to /home/<user>/.composer.

So depending on your Linux distribution, it can either be `~/.config` or `~/.composer`. I also remember having some issues with this config path in the past. So I think it's ok to add a command line (maybe the one you posted but with a grep to only show the interesing path?) in our documentation to help users add the correct path in the $PATH env var.

Would you mind to submit such a PR? 🙂

**Comment by thedomeffm** [comment]
https://github.com/jolicode/castor/pull/211 😄
