### ISSUE TITLE
Depend on the Symfony Command Profiler for an out-of-the-box debugging panel

### ISSUE THREAD

**Issue by tigitz** [jolicode/castor#219]
While reviewing the introduction of the EventListener feature, I realized it's yet another Symfony package integrated into Castor, along with HttpClient, Cache, Console, and the Monolog bridge.

This made me think about leveraging the recently added [Command Profiler](https://symfony.com/blog/new-in-symfony-6-4-command-profiler) for built-in profiling tools. These could provide valuable traces, logs, and performance tracking out-of-the-box for what happens inside our Castor apps.

For example [I suggested to add debug logs while dispatching / listening,](https://github.com/jolicode/castor/pull/218#discussion_r1445997448) something that usually comes for free in Symfony apps.

Castor might even implement its own DataCollector to profile its engine.

I'm uncertain about the potential impact on the codebase (I guess the GlobalHelper would have to be refactored to a Symfony Container ?), so I view this issue more as an idea for discussion.

**Comment by lyrixx** [comment]
It's a good idea! 

But actually, I'm not sure this is really needed. More over, the current profiler is almost impossible to adapt to such application. (Symfony is not ready for that). It'll may be possible in 7.1, but not sure.

Finally, this will bring too much code, for a feature not so commun. Thus the phar will be much heavier.

So I'm -1 for now.

I'm sorry to close your issue! But please, keep contributing on this project. This is much appreciate!
