### ISSUE TITLE
The test autogeneration script seems to break the output files

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#236]
The test autogeneration script seems to break the output files, or at least change the output format, is this normal?

![image](https://github.com/jolicode/castor/assets/72203064/86517455-2948-4fab-b66c-8fce1e9e10f9)

The problem is only present after the update to 6.4.*. ["update to symfony 6.4.*"](https://github.com/jolicode/castor/pull/224) commit 06661100

EDIT :

The problem is present here too : https://github.com/jolicode/castor/pull/235/files#diff-fc5f4f1650c6b6065733fe148d65106f2953ba440c80b9cc33c03d7c4038421a

I have identified the package : `symfony/console`, version `6.4.1` work fine like before

The problem come from this change https://github.com/symfony/symfony/pull/52940

You can fix this by removing the `no-ansi` option in `bin/generate-tests.php` but that will add the option to all existing tests so I'll let you decide how you want it to go but that was my investigation if it can helps 😄

**Comment by lyrixx** [comment]
see #237

**Comment by lyrixx** [comment]
can you rebase and tell me if it's okay now? if it's okay, you can close the issue. thanks
