### ISSUE TITLE
Add macos-arm64 target

### ISSUE THREAD

**Issue by ruudk** [jolicode/castor#283]
I noticed that the Castor binary for macOS is AMD64, but I think that should be ARM64, because Apple moved to Apple Silicon for the whole line up.

**Comment by lyrixx** [comment]
Good catch. IIRC We have an OS divergence for the [watch binary](https://github.com/jolicode/castor/tree/main/tools/watcher).

(Un)fortunatelly, I don't own a Mac, so I cannot help here. Do you want to give it a try?

see 
* https://github.com/jolicode/castor/blob/main/tools/watcher/castor.php
* https://github.com/jolicode/castor/blob/main/tools/phar/box.darwin-amd64.json

**Comment by ruudk** [comment]
Sure, could you give a bit more instructions on what to do? 

I pulled the repo and ran `go build -o bin/watcher-darwin -ldflags="-s -w" main.go`. That works.

❯ file ./bin/watcher-darwin
./bin/watcher-darwin: Mach-O 64-bit executable arm64

**Comment by ruudk** [comment]
I think we need to do it like this:

```diff
#[AsTask(description: 'Build watcher for MacOS system')]
function darwin()
{
-    run('go build -o bin/watcher-darwin -ldflags="-s -w" main.go', environment: ['GOOS' => 'darwin', 'CGO_ENABLED' => '0'], path: __DIR__);
+    run('go build -o bin/watcher-darwin-amd64 -ldflags="-s -w" main.go', environment: ['GOOS' => 'darwin', 'GOARCH' => 'amd64', 'CGO_ENABLED' => '0'], path: __DIR__);
+    run('go build -o bin/watcher-darwin-arm64 -ldflags="-s -w" main.go', environment: ['GOOS' => 'darwin', 'GOARCH' => 'arm64', 'CGO_ENABLED' => '0'], path: __DIR__);
}
```

**Comment by lyrixx** [comment]
Exactly 👍🏼 ; then you'll have to upates all files I linked, and commit your binary

**Comment by ruudk** [comment]
I'm getting this
![Screenshot 2024-02-16 at 13 08 08@2x](https://github.com/jolicode/castor/assets/104180/823727ca-7b4e-4717-8dce-6b5eff3d9f1b)

**Comment by ruudk** [comment]
I wonder if the AMD64 version gives the same warning?

**Comment by ruudk** [comment]
Yes same issue with the darwin watcher from the latest release.

**Comment by ruudk** [comment]
When I manually allow it via `System Preferences > Privacy & Security` it works. For both AMD64 and ARM64 😊

**Comment by ruudk** [comment]
I think this should do it: https://github.com/jolicode/castor/pull/284

**Comment by lyrixx** [comment]
Fixed in #284

**Comment by lyrixx** [comment]
BTW, before we release castor, you can grab the phar here: https://github.com/jolicode/castor/actions/runs/7931317051

**Comment by ruudk** [comment]
It works!
```
❯ ./castor.darwin-arm64.phar hello

Hello Ruud!
===========
```

Also tested the watcher! 

All good

**Comment by ruudk** [comment]
Btw, does this mean that this PHAR runs completely independent of PHP on the machine? Can I pull this PHAR in a empty machine, and it will just work?

**Comment by pyrech** [comment]
No, the phar is "only" an archive containing the PHP application. But it still needs PHP to exec.

But the static compilation feature we have started to support (see https://github.com/jolicode/castor/blob/main/doc/going-further/compile.md) will allow to provide binaries that embed PHP, and in this case, yes, the binary will work out of the box on a an empty machine :)

**Comment by ruudk** [comment]
Amazing. Are you also going to release a static castor binary like that? So that I can pull that, and use it to run my `castor.php` file? Or does `castor.php` needs to be compiled together with the rest?

**Comment by pyrech** [comment]
This is what we have in minds, yes. But it's not ready yet :wink:

**Comment by ruudk** [comment]
Exciting, can't wait for that 🎉
