### ISSUE TITLE
Repack command: merge local box config?

### ISSUE THREAD

**Issue by SebLours** [jolicode/castor#305]
Hello!

I encounter a problem with the `repack`command.

I use `Twig` to render complex config files.  
`Twig` has a `\Twig\TwigTest` class to implement the test operator.

With the current `box` configuration, the `Test` files are blacklisted
https://github.com/jolicode/castor/blob/main/tools/phar/box.linux-amd64.json#L9

When i repack my app, i have an error `Class "Twig\TwigTest" not found`

I can go around this problem adding this configuration in the Castor box config file:
```json
"files": [
    "../../../vendor/twig/twig/src/TwigTest.php"
],
```

Did you think it could be a feature to allow merging a local box config file?

Thanks!

**Comment by lyrixx** [comment]
> Did you think it could be a feature to allow merging a local box config file?

Yes 👍🏼 Do you want to work on a PR?

Thanks for the bug report

**Comment by SebLours** [comment]
> Yes 👍🏼 Do you want to work on a PR?

Yes, I can!

**Comment by SebLours** [comment]
@lyrixx I propose this PR #318 

Did you think this simple solution is convenant? or introduce an option in the repack command?

**Comment by jacquesbh** [comment]
I literally have this issue right now ^^.

Thank you @SebLours for the tips!
