### ISSUE TITLE
When `exit_code` or `run` is invoked, the task does not complete (`fwrite()` error)

### ISSUE THREAD

**Issue by cedx** [jolicode/castor#339]
Castor 0.14.0 (Phar)
PHP 8.3.4
PowerShell 7.4.1 on Windows 11

Everytime I try to run a task that includes a call to `run()` or `exit_code()`, the task does not complete. I have to either `Ctrl+C` or press `Enter` to exit the task, and then an error is displayed:

```
In AbstractPipes.php line 139:

  Notice: fwrite(): Write of 2 bytes failed with errno=22 Invalid argument
```

The command is OK, because I can see its output right after this error message.
A sample task triggering this error:

```php
#[AsTask]
function phpVersion(): void {
  run("php --version"); // Using a string or an array as argument does not change anything.
}
```

This error does not occur if I use Symfony Process directly (i.e. `(new Process(["php", "--version"]))->run()`).

**Comment by lyrixx** [comment]
Thanks for the report. 

I don't use windows, but we'll find a way to help you!

In the meantime, if you can try to debug it, it would be awesome. If not, don't worry!

**Comment by cedx** [comment]
A first track: it is related to the PTY.
If I disable PTY (either globally via a context, or locally in the `run()` call), everything is OK.
