### ISSUE TITLE
Allow moving `.castor.stub.php` to `castor` directory when available

### ISSUE THREAD

**Issue by ruudk** [jolicode/castor#348]
Keeps the project root clean.

**Comment by pyrech** [comment]
That's something I planned to propose once imports (#297) are merged, as it will provide a `.castor` directory at the root

**Comment by lyrixx** [comment]
I think we could already accept a PR for this issue. It won't conflict.

However, as you said in the title, we will still generate it in the root dir. But we'll check for both locations.

Would you want to do it?
