### ISSUE TITLE
Documentation deployed independently before release

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#363]
Hello,

Is it normal for the documentation to be deployed independently of the release of GitHub ?

For example, documentation on installation via installer is currently present [see here](https://castor.jolicode.com/getting-started/installation/#with-the-installer), but should only appear when release 0.15 comes out, right? (even if it works in the current case).

If a new feature is deployed, the documentation will be ahead of the release ^^

**Comment by lyrixx** [comment]
Indeed, the doc might be in advance of phase. But it's not a big deal IMHO. We release quite often.

And the installer is already available 😎 

We could add `versionadded` admonition, like in Symfony, but it's a big maintenance effort. I'm not sure it's worth it.

Another option is to deploy the doc only when a new release is done. But we continuously enhance it. So it would be a shame to loose this quick iteration loop.

Finally, we could add a version selector. I don't know if it's easy do to with mkdoc (cc @pyrech) and I'm not sure it worth the maintenance burden. 

More over, we try very hard to not break the BC, so, again, it's not a big deal.

**Comment by TheoD02** [comment]
Ok thanks for the answer, it was just to make sure it was a choice, and known ^^

That's what I thought, it all depends on the case, it's especially in the case of new feature it can disturb (but remains rare)

There seems to be something on the mkdocs side that's pretty easy to set up (https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)

**Comment by lyrixx** [comment]
I let @pyrech AKA the "doc master" take the final decision 🤓 📖

**Comment by pyrech** [comment]
I don't think the public API will change quite often (once the V1 is released). So the version selector could be a bit overkill for us (and would force us to maintain almost the same documentation for each available version).

I think the best choice (in term of maintenance for us and even for ux on the doc website), at our scale, will be to add some admonitions when new functions/feature are added. But again, only once v1 is released. This will also allow us to continuously enhancing the doc easily, without having to worry about the documentation created for previous version.
