### ISSUE TITLE
Allow user to choice where to create root `castor.php` file

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#364]
Hello 😄 

What do you think about letting the user choose where he wants to create the root `castor.php` file?

Something like:
![image](https://github.com/jolicode/castor/assets/72203064/80c82f8c-2005-49d4-ae11-5fbd65c67cc7)

**Comment by lyrixx** [comment]
I think it's useless 😅 Less option == better DX ! 

But it looks like you already do all the code, and it breaks my heart to throw away your work... So if you want, you can open a PR.

> [!NOTE]
> the default way is the `castor.php` file


In the meantime, I'm closing this issue as this is not something we really want
