### ISSUE TITLE
[REQUEST] Be able to define the order of commands when displaying the listing

### ISSUE THREAD

**Issue by mark-alexandre** [jolicode/castor#388]
Hi,

At the moment, when running `php castor` in order to list the available commands by namespace, it seems that a sort() is executed. Is it possible to add an option in castor in order to choose manually the display order of this command... or at least display the list in the order which is defined in the file (which will be easier to implement).

As an example, imagine a simple file like this :

```
<?php

namespace Docker;

use Castor\Attribute\AsTask;
use function Castor\run;

#[AsTask(description: 'Lancement du docker compose associé au projet')]
function up(): void
{
    run('docker-compose up');
}

#[AsTask(description: 'Fermeture du docker compose associé au projet)')]
function down(): void
{
    run('docker-compose down');
}

#[AsTask(description: 'Suppression des volumes et des images locales (ex: pour repartir sur une BDD vide')]
function reset(): void
{
    run('docker-compose down -v --rmi local');
}
```

This will result in this list :

![image](https://github.com/jolicode/castor/assets/61732473/ff2ff37f-8b9a-4d8e-a7a6-cab4838faa02)

The goal here is to to display these commands in the order they are declared in the file instead. I personnally prefer group commands by the type of action they are related to (up() and down() have the same scope, reset another one). This will result in a list like this :

- up
- down
- reset

Do you get it ? This is more a quality of life update that I'm requesting.

Regards.

**Comment by lyrixx** [comment]
It might be nice but since we use symfony under the hood, it's not possible. Sorry

You can open an rfc in symfony/symfony instead

**Comment by mark-alexandre** [comment]
Allright, I got you. Thanks for the answer.
