### ISSUE TITLE
Issue when using `import` from a git repository

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#395]
When utilizing the `import` statement to import helpers from a git repository, the `import` functionality may not behave as expected when updating the repository.

The `import` operation involves downloading the repository and storing it in the `vendor` directory of the project. However, when pushing fixes and updates the repository, the `import` statement not fetching the latest version.

This issue is not strictly related to `castor` but rather appears to be more of a `composer` problem.

#### Steps to Reproduce the Issue:

```php
import('package://theod02/castor-class-task', source: [
    'url' => 'https://github.com/TheoD02/castor-class-task.git',
    'type' => 'git',
    'reference' => 'main',
]);
```

```bash
# Will download remotes and all files
castor test
```

After making a mistake and pushing a fix to the repository `castor-class-task`:

```bash
# Should fetch the new version
castor --update-remotes
```

However, in this scenario, Composer have cached the previous version. To resolve this, you may need to remove the `vendor` directory and run `composer clear-cache`, then re-run `castor` to import the remotes again.

Is the expected behavior ?

**Comment by lyrixx** [comment]
Hello, Thanks for the bug report.
I notice something similar too.

Could you try https://github.com/jolicode/castor/pull/396, and tell me if it's fixed?

**Comment by TheoD02** [comment]
> Hello, Thanks for the bug report. I notice something similar too.
> 
> Could you try #396, and tell me if it's fixed?

PR #396 doesn't seem to fix the problem at the moment

**Comment by lyrixx** [comment]
With the new PR, `castor --update-remotes` always force a composer refresh (it was not the case before). So we cannot do anything here :/

**Comment by TheoD02** [comment]
> With the new PR, `castor --update-remotes` always force a composer refresh (it was not the case before). So we cannot do anything here :/

The problem seems to be with the structure used with the composer repositories for git.

When the `package` type is used in this case it doesn't work.

But for example, if I use this structure, it works:

```json
{
    "description": "This file is managed by Castor. Do not edit it manually",
    "config": {
        "sort-packages": true
    },
    "replace": {
        "castor": "v0.15.0"
    },
    "require": {
        "theod02\/castor-class-task": "dev-main",
        "theod02\/castor-docker": "dev-main"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https:\/github.com\/TheoD02\/castor-class-task.git"
        },
        {
            "type": "git",
            "url": "https:\/github.com\/TheoD02\/castor-docker.git"
        }
    ]
}
```

The actual format is : 

```json
{
    "description": "This file is managed by Castor. Do not edit it manually.",
    "config": {
        "sort-packages": true
    },
    "replace": {
        "castor\/castor": "v0.15.0"
    },
    "require": {
        "theod02\/castor-class-task": "v1",
        "theod02\/castor-docker": "v1"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "theod02\/castor-class-task",
                "version": "v1",
                "source": {
                    "url": "https:\/\/github.com\/TheoD02\/castor-class-task.git",
                    "type": "git",
                    "reference": "dev-main"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "theod02\/castor-docker",
                "version": "v1",
                "source": {
                    "url": "https:\/\/github.com\/TheoD02\/castor-docker.git",
                    "type": "git",
                    "reference": "dev-main"
                }
            }
        }
    ]
}
```

**Comment by lyrixx** [comment]
Why do you use 

> ```
> import('package://theod02/castor-class-task', source: [
>     'url' => 'https://github.com/TheoD02/castor-class-task.git',
>     'type' => 'git',
>     'reference' => 'main',
> ]);
> ```

if the repository is a valid composer package?

You can use 
```
import('composer://theod02/castor-class-task', version: 'dev-main@dev');
```

**Comment by TheoD02** [comment]
> Why do you use
> 
> > ```
> > import('package://theod02/castor-class-task', source: [
> >     'url' => 'https://github.com/TheoD02/castor-class-task.git',
> >     'type' => 'git',
> >     'reference' => 'main',
> > ]);
> > ```
> 
> if the repository is a valid composer package?
> 
> You can use
> 
> ```
> import('composer://theod02/castor-class-task', version: 'dev-main@dev');
> ```
> 
> [see the documentation](https://castor.jolicode.com/going-further/extending-castor/remote-imports/?h=composer)

Hello,

In my personal case, yes, in my professional project, we will continue to use git, I think for now composer package is not planned

What would be the impact of this change?

**Comment by lyrixx** [comment]
You could add a composer.json in your git repo and use the intermediary syntax. It should fix you use case

**Comment by TheoD02** [comment]
> You could add a composer.json in your git repo and use the intermediary syntax. It should fix you use case

I'll give it a try and let you know
