### ISSUE TITLE
Issue with import and composer class auto-loading Issue

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#397]
### Description
When attempting to load classes, issues arise under specific circumstances, causing import failures and class loading errors. 

### Use Case Example
When utilizing classes or traits, import processes may fail due to the non-existence of the referenced classes. 

### Steps to Reproduce
1. Clone the repository [castor-issue-reproducer](https://github.com/TheoD02/castor-issue-reproducer/tree/main).
2. Checkout the commit `903a52a7860899f8b93ca3d5f65e6245ee223e16`.
3. Execute `castor install`.

### Expected Behavior
During step 3, the command should execute successfully without errors.

### Actual Behavior
The command fails due to the absence of the vendor directory.

### Workaround
To address the issue temporarily:
1. Comment out lines 20 to the end of the file.
2. Re-run the `castor install` command.
3. Import functionality should now work.
4. Uncomment the previously commented lines to restore the code to its original state.
5. Expected case work fine

### Additional Note
Despite successful class loading, the command may still fail due to the non-existence of the container, which is expected behavior as no container is present.

### Secondary Issue
Another issue arises when utilizing split files for clearer code organization. After fetching the vendor and attempting to execute `castor install` on the commit `049fc8f9c7e96c0bf008f482239ea37881803c7d`, the `Composer.php` is imported, but Composer fails to resolve the class, resulting in the following error message:
```
Attempted to load trait "RunnerTrait" from namespace "TheoD02\Castor\Docker".
Did you forget a "use" statement for another namespace?
```

**Comment by lyrixx** [comment]
What you made cannot work by design.

**Comment by lyrixx** [comment]
I have an idea to make it work, but it's not planned yet. And it will be hard. I'm not sure we want to support that for now

The idea is to parse files before require them and extract import asap, load vendor, then require the files

**Comment by TheoD02** [comment]
In fact, I hadn't yet looked for a solution to the problem before raising the issue.

I've just been looking for a way to do it.

The current state is :

I've added an autoload (psr-4) in castor vendor composer.json : 

```json
    "autoload": {
        "psr-4": {
            "Castor\\User\\": "."
        }
    },
```

As a result, every task is prefixed by `castor:user` in its namespace, so I've deleted it. (I don't know for now if a better way is possible)

I delayed the import of tasks except for the remote ones.

It seems to work overall but one point is not correct in the call to `get_defined_functions()` for the moment which is probably not totally correct from what I've seen with the castor examples. But has the honour of working for the current case 

The reproduction repo: https://github.com/TheoD02/castor-issue-reproducer/tree/import-with-namespace

Here is the diff based on the #396 implementation https://github.com/jolicode/castor/commit/17ca1a79a1c2aeed6d449fa391e8d5f66c2a5f25

![image](https://github.com/jolicode/castor/assets/72203064/981cf82d-2393-4394-920d-bff730d39c58)

**Comment by lyrixx** [comment]
The second issue has been fixed by your PR. Thanks

For the first issue, you can wrap the problematic code in a `if (class_exists(CastorDockerContext::class)) { ...` 

Thanks for the report, and for the research. I'm closing it, but don't hesitate to open a new issue if something does not work after the merge of #396

**Comment by TheoD02** [comment]
Hello,

The issue is not the same that one corrected by PR #394 (concern internal composer files exclusion)

In this issue, problem come from imported packages

If you want the import to be done without having to comment out the code, you have to use the `delayedImport` implementation. 

see: https://github.com/jolicode/castor/commit/17ca1a79a1c2aeed6d449fa391e8d5f66c2a5f25#diff-79a7bb5a5a2ea74a5bbe3c2b15f787e20280b8e1b532270ab5fbc47112292167R23

To use an external library, you also need the autoload part:
https://github.com/jolicode/castor/commit/17ca1a79a1c2aeed6d449fa391e8d5f66c2a5f25#diff-731df294df988467f59d988f6fbf65b34098f76dd043d84358db9dccf834b317R28

If you have a little time to give me some feedback, if the implementation doesn't look too bad with the new import system?

I know it's not optimal at the moment, but if the direction is pretty good I can open a PR, thanks 😄

**Comment by TheoD02** [comment]
> @TheoD02 ok, I have merged the kernel refacto. I still don't understand your issue :/
> 
> Could you open a PR with your patch, and a simple producer? Thank

Hello,

So the PR seems to have corrected some of the problems after retesting ! I may have tested your branch too early, but the latest changes seem to be correct and no longer cause any problems.

For example, let's imagine we want to use the `doctrine/collections` library to manipulate arrays.

`castor.php` will look like :
```php
<?php

use Castor\Attribute\AsTask;

use Doctrine\Common\Collections\ArrayCollection;
use function Castor\import;
use function Castor\io;
use function Castor\capture;

import('composer://doctrine/collections', version: '^2.0');
import(__DIR__);

#[AsTask()]
function test(): void
{
    $collection = new ArrayCollection(['a', 'b', 'c']);

    io()->title('Ramsey Collection Items');
    foreach ($collection as $item) {
        io()->writeln($item);
    }
}
```

When I call `castor test` everything is correct. With or without vendor installed it will work like expected now. :confetti_ball: 

Before the refacto the following error was thrown (after vendor fetched): 
![image](https://github.com/jolicode/castor/assets/72203064/8d9d6161-81b6-43d7-9137-d815fe3ac017)

----

My second case is like the first one, but only move this logic to a class in another file.

My `castor.php` look like this: (`.castor/castor.php`)
```php
// file location: .castor/castor.php
<?php

use Castor\Attribute\AsTask;

use Doctrine\Common\Collections\ArrayCollection;
use function Castor\import;
use function Castor\io;
use function Castor\capture;

import('composer://doctrine/collections', version: '^2.0');
import(__DIR__);

#[AsTask()]
function test(): void
{
    test_class()->loop();
}
```

And my `Test.php` file that look like that:

```php
// file location: .castor/Test.php
<?php

use Castor\Context;
use Doctrine\Common\Collections\ArrayCollection;
use function Castor\io;

class Test
{
    public function loop(): void
    {
        $collection = new ArrayCollection(['a', 'b', 'c']);

        io()->title('Ramsey Collection Items');
        foreach ($collection as $item) {
            io()->writeln($item);
        }
    }
}

function test_class(): Test
{
    return new Test();
}
```

And the good news is, that case work too now.
I don't know why yet. I haven't reviewed your code exactly yet. But it seems to have done the trick :smile: 
I hope my explanations have brought more clarity to the use case.

----

But my last problem now seems to be related to the class, which seem to be parsed before the autoload is required. (I think)
I'll look for a solution to this problem on my own.

This should also correct the case of `Attempted to load trait "RunnerTrait" from namespace "TheoD02\Castor\Docker".`

For example this simple re-producer will fail

```php
<?php

use Castor\Attribute\AsTask;

use Castor\Context;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Symfony\Component\Process\Process;
use function Castor\import;
use function Castor\io;
use function Castor\capture;

import('composer://doctrine/collections', version: '^2.0');
import(__DIR__);

#[AsTask()]
function test(): void
{
    $collection = new ArrayCollection(['a', 'b', 'c']);

    io()->title('Ramsey Collection Items');
    foreach ($collection as $item) {
        io()->writeln($item);
    }
}

class TestSelectable implements \Doctrine\Common\Collections\Selectable
{
    public function matching(Criteria $criteria): ArrayCollection
    {
        return new ArrayCollection(['a', 'b', 'c']);
    }
}
```

Error thrown : 
![image](https://github.com/jolicode/castor/assets/72203064/b09d1202-0304-4513-9ce5-cab98346915a)

I think we can close the issue, the case of the class is different from the first reporter case.

**Comment by TheoD02** [comment]
Ok I looked for a solution without too much impact and complexity for the moment that would be a kind of bootstrap file a bit like `phpunit` does. This could be used to import any necessary files before require the `castor.php` entrypoint.

Here the branch diff:
https://github.com/jolicode/castor/compare/main...TheoD02:castor:fix/allow_usage_of_classes_with_extends_implements_traits

What do you think of this approach?

If you comment the line `$this->autoRequireBootstrapFile();` on Kernel.php line 55. The error should appear when no vendor was fetched like : 
![image](https://github.com/jolicode/castor/assets/72203064/0680b57a-5cb6-4c2a-92f2-734d4fc38270)

**Comment by lyrixx** [comment]
Nice 🎉 ! Very glad some issues have disappeared.

For the last one, I'm very reluctant : 

* this introduce a convention (and I would like to avoid convention as much as possible)
* there is more code to maintain
* but above all, this is already doable in userland with a simple `class_exist()`

```php
// .castor/castor.php
if (class_exist(XXX:class)) {
  import(__DIR__ . '/depends_on_class.php');
}
```

**Comment by TheoD02** [comment]
I agree with that, but I'm not sure this solution works, as the autoload will be loaded after the import anyway. 

```php
// file: castor.php
<?php

use Castor\Attribute\AsTask;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use function Castor\import;
use function Castor\io;

import('composer://doctrine/collections', version: '^2.0');
import(__DIR__);

#[AsTask(description: 'Use classes that use imported from remote packages')]
function collection(): void
{
    $collection = new ArrayCollection([1, 2, 3, 4, 5]);

    io()->title('Collection Items');
    foreach ($collection as $item) {
        io()->writeln($item);
    }

    io()->title('Collection Items (matching)');
    $collection = (new TestSelectable())->matching(Criteria::create());

    var_dump($collection->toArray());
}
```

```php
// file: Test.php
<?php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use function Castor\io;

if (class_exists(Selectable::class)) {
    io()->writeln('Selectable class exists !');

    class TestSelectable implements Selectable
    {
        public function matching(Criteria $criteria): ArrayCollection
        {
            return new ArrayCollection(['a', 'b', 'c']);
        }
    }
}
```

Result as : 
![image](https://github.com/jolicode/castor/assets/72203064/d38ba0ec-70aa-494a-a77f-b16212916f7d)

I think this is due to the load of entrypoint when calling `Kernel::boot()`
https://github.com/jolicode/castor/blob/0a58ca600a1fd221d86582c0328179c15780aab5/src/Kernel.php#L58-L67

`$this->load(...)` will require the `castor.php` and import other files before the require of `autoload.php`

And autoload is required just after by calling `$this->packageImporter->fetchPackages()`
https://github.com/jolicode/castor/blob/0a58ca600a1fd221d86582c0328179c15780aab5/src/Import/Remote/PackageImporter.php#L88

**Comment by lyrixx** [comment]
See #403. Now it works 🎉 
but tasks are not loaded on the very first run!

**BUT**... I made somethings : 
![image](https://github.com/jolicode/castor/assets/408368/d6b72f71-dc36-4cc9-beef-7caa763fc011)
see #404

**Comment by TheoD02** [comment]
> See #403. Now it works 🎉 but tasks are not loaded on the very first run!
> 
> **BUT**... I made somethings : ![image](https://private-user-images.githubusercontent.com/408368/321330623-d6b72f71-dc36-4cc9-beef-7caa763fc011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzI3MTEsIm5iZiI6MTcxMjc3MjQxMSwicGF0aCI6Ii80MDgzNjgvMzIxMzMwNjIzLWQ2YjcyZjcxLWRjMzYtNGNjOS1iZWVmLTdjYWE3NjNmYzAxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxODA2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWRhNDVlYWVjMDU5NzA5ZDQ2NzhjMDk4MDMzOGI0MTU4YzMyNmQ5NDg3ZjA1MDc5Zjg0OTMxZTQzODYyMjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZMs12Qf-9lP98FbUmnyZRO-QvLzjjN05kfCnYX3OH0w) see #404

Thanks for the fix and your times ! 🤟 

That looks good for me, and open to more usage 😄

**Comment by lyrixx** [comment]
hello @TheoD02 ; could you test with the new stack?

**Comment by TheoD02** [comment]
Hello,

I'd say yes, but not optimal. In the sense that I have to re-import `autoload.php` file.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

import('composer://theod02/castor-class-task');
import('composer://theod02/castor-docker');

import(__DIR__);

```


That should be handled by : 

https://github.com/jolicode/castor/blob/636a2464bfaddf6e301465c7accf4ee1f0d1a429/src/Kernel.php#L65

**Comment by TheoD02** [comment]
Just retested and PR #426 have fixed the issue ! 🥳

Thanks for your time and hard work 🚀😃

**Comment by lyrixx** [comment]
Thanks for helping us for enhancing this feature. We have now a god design, and it's thanks to you. 💛
