### ISSUE TITLE
Issue using "castor start" on linux without php 

### ISSUE THREAD

**Issue by nissim94** [jolicode/castor#398]
![image](https://github.com/jolicode/castor/assets/7337880/794f538f-a7eb-44c5-9b12-d1652dc70f34)

the related file ".exe" seems to be missing.

I looked into the vendor directory and the [jolicode/jolinotif](https://packagist.org/packages/jolicode/jolinotif) package is missing. Also in the related composer.json is missing too.

**Comment by pyrech** [comment]
Hi @nissim94, thanks for your issue.

Here, JoliNotif seems to fail retriving a binary that should be used on Windows but your issue is about Linux, so I guess you are running castor inside Windows WSL.

How did you install Castor?

In your case, you should run use the phar built for Windows, not a phar built for a Linux nor one of the statix binary built for Linux.

**Comment by pyrech** [comment]
> I looked into the vendor directory and the [jolicode/jolinotif](https://packagist.org/packages/jolicode/jolinotif) package is missing. Also in the related composer.json is missing too.

The vendor directory mentioned in the exception is the one inside the Castor project, not the vendor directory of your project, so nothing wrong here I guess

**Comment by nissim94** [comment]
> Hi @nissim94, thanks for your issue.
> 
> Here, JoliNotif seems to fail retriving a binary that should be used on Windows but your issue is about Linux, so I guess you are running castor inside Windows WSL.
> 
> How did you install Castor?
> 
> In your case, you should run use the phar built for Windows, not a phar built for a Linux nor one of the statix binary built for Linux.

its installed using this method : https://castor.jolicode.com/getting-started/installation/#binary-for-linux

**Comment by lyrixx** [comment]
What OS a you running?

**Comment by nissim94** [comment]
> Hi @nissim94, thanks for your issue.
> 
> Here, JoliNotif seems to fail retriving a binary that should be used on Windows but your issue is about Linux, so I guess you are running castor inside Windows WSL.
> 
> How did you install Castor?
> 
> In your case, you should run use the phar built for Windows, not a phar built for a Linux nor one of the statix binary built for Linux.

its installed using this method : https://castor.jolicode.com/getting-started/installation/#binary-for-linux under WSL container

**Comment by nissim94** [comment]
> What OS a you running?

running win 11 with WSL and ubuntu 22.04 as distro.

**Comment by lyrixx** [comment]
okay, so it looks like you ticket title is good enough.

As you are using windows, you cannot use the build for linux. You need the one for windows. See [the documentation](https://castor.jolicode.com/getting-started/installation/#phar-for-windows)
