### ISSUE TITLE
Problem with `vsc` import and Github API Limit

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#410]
Hi, there,

I had a problem using a composer package via `vcs` and `github`.

For example with this import:
```php
import('composer://theod02/castor-class-task', version: 'dev-main@dev', vcs: 'https://github.com/TheoD02/castor-class-task.git');
```

This works until you reach the github limit. It works fine as soon as you define the token too. 

![image](https://github.com/jolicode/castor/assets/72203064/158a8840-cbbe-4c4e-92ab-7d7ea3a1aff9)

But the problem is that by default the composer output is captured separately from the castor output. So to get the output that tells me to use a token, I had to change the output used by composer to castor.

As composer don't exit with error code, nothing appear and the download state is locked on the same state without showing anything that indicate that something need to be do by the end user

Adding the `--no-interaction` option to composer seems to correct the problem and composer seem to fallback on my SSH key.

**Comment by pyrech** [comment]
Fixed in #411
