### ISSUE TITLE
Specifying path for box executable in RepackCommand

### ISSUE THREAD

**Issue by andreacivita** [jolicode/castor#416]
Hi,

I was repackaging my project and followed the local installation guide for Box as outlined here: [Box Installation Guide](https://github.com/box-project/box/blob/main/doc/installation.md#composer). 

 Issue Encountered:
I observed that the RepackCommand does not allow specifying the path to the box executable as argument. This limitation prevents using the locally installed Box dependency directly.

Are you considering adding functionality to specify a custom path for the Box executable in the RepackCommand and / or willing to accept a PR?

Thank you very much!

**Comment by lyrixx** [comment]
Yes. Feel free to open a pr 👍🏼 
Thanks

**Comment by andreacivita** [comment]
Thank you, i will submit a pr as soon as possible.

Regarding the PATH, I believe specifying the path directly in the program call offers greater isolation and reproducibility, since I have all the necessary tools to run Castor (and repack it) locally at the directory level. 
While adding Box at the PATH level was a valid option, I found that for my specific use case, specifying the path directly was more appropriate.

**Comment by arnolem** [comment]
Perhaps we should take the opportunity to also configure the destination folder (Ex: /dist/).
I searched but couldn't find if it was possible.
What do you think ?

**Comment by lyrixx** [comment]
I am going to close here for now due to the lack of feedback. But please, open a PR directly 👍🏼
