### ISSUE TITLE
Make `BeforeBootEvent` non-internal ?

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#441]
Hi there,

What do you think about changing the `BeforeBootEvent` from internal to public so that it can be accessed from a castor application?

Here is my use case:
Before importing from the remote, I want to make sure the authentication for composer is set up, for example

```php
#[AsListener(\Castor\Event\BeforeBootEvent::class)]
function check_composer_auth(): void
{
    $home = Path::getHomeDirectory();
    $composerAuthFile = "{$home}/.composer/auth.json";
    if (file_exists($composerAuthFile) === false) {
        io()->warning('Composer auth file not found.');
        $token = io()->ask('Token');
        $password = io()->ask('Password');
        // add creds to auth file
    }
}
```

**Comment by lyrixx** [comment]
composer will do that anyway?

**Comment by lyrixx** [comment]
Anyway, It won't work since application (userland) file has not been loaded yet.

**Comment by TheoD02** [comment]
> composer will do that anyway?

Just for context 

Yes he does. But in our use case I want to define it in a local file on host machine for use in docker with volume. 
And in this case I have to do it in each container. 
I can't use SSH keys (ops restriction :sob:).

But in the end, I will rely on `BeforeExecuteTaskEvent` which will execute the logic before `start` task (if this helps someone with a similar problem).
