### ISSUE TITLE
Using .env files with phar file

### ISSUE THREAD

**Issue by arnolem** [jolicode/castor#442]
Hello,

I don't understand how to use .env with .phar applications

1- Create a task into `/projets/castor-test/castor.php`
```php
<?php

use Castor\Attribute\AsTask;

use function Castor\load_dot_env;

#[AsTask]
function test(): void
{
    dump(load_dot_env());
}
```

2- Create a .env file `/projets/castor-test/.env`
```
TEST=TOTO
```

3- Repack with castor
```bash
vendor/bin/castor repack
```

the .env is not embedded in the phar. probably normal?
![image](https://github.com/jolicode/castor/assets/2263103/954fd5bf-0afa-4b78-8215-9fc3c785edd9)

4- Use the test Task
```bash
./my-app.linux.phar test
```

An error occurred
```
Unable to read the "/projets/.env" environment file. 
```

But why the .env file is load from ``/projets`` on not from the current directory ``/projets/castor-test/`` ?

Thanks. ♥️

**Comment by lyrixx** [comment]
I guess the `.env` file is searched inside the phar and not on your disk.
AND it's not inside the phar (Not packing it may be an error)

I imagine there are other similar issues with repacked application.

But this is not really easy. It's hard to tell if the repacked app should search on disk, on in the phar... I have no answer for now...

Maybe someone have a nice point of vieux to share!

**Comment by lyrixx** [comment]
@joelwurtz That means we have to embed everything 😬. I don't like that.

But I just test, and indeed there is an issue with `.env`. I'm on it

**Comment by arnolem** [comment]
Thanks @lyrixx 👏
