### ISSUE TITLE
`notify` context is not super clear about expected behavior

### ISSUE THREAD

**Issue by TheoD02** [jolicode/castor#444]
Hi, there,

As I indicated in the title the `notify` parameter in the context can be confusing.

What I mean is that when `notify` is set to `false` then I would expect no notification to be sent.

But today `false` means that functions based on `run` will not send a notification, and if true they will send a notification internally.

What do you think about changing the definition of notify?

----

What i have in mind is :

The default value should be null.

From:
https://github.com/jolicode/castor/blob/642a6a902dfffa5e00c437240bf03d6ceef13686/src/Context.php#L29

To:
```php
public readonly ?bool $notify = null,
```

So :
`null` => No notification triggered by the `run` method. But notifications triggered by the user will be displayed.
`false` => No notification displayed for any `notify` call, whether internal or user.
`true` => Internal notifications and user trigger notifications are displayed.

**Comment by lyrixx** [comment]
> What do you think about changing the definition of notify?

make sens 👍🏼
