### ISSUE TITLE
How can I change the terminal working directory ?

### ISSUE THREAD

**Issue by arnolem** [jolicode/castor#445]
For instance:

```
/home/user/$ castor goto:projet-a
Success
/var/www/projects/projet-a
```

I tried : 
```php
run('cd /var/www/projects/projet-a');
run('', workingDirectory: '/var/www/projects/projet-a');
run('goto-projet-a.sh');
```

but nothing works 🙄

**Comment by TheoD02** [comment]
Hi there!

I'm not sure if I understood the request completely but from what I understand you want to execute an command in a specific folder?

For example the following command will output the content of `/home/user/my-directory`

`run('ls', workingDirectory: '/home/user/my-directory');`

But in the second case, and you want to change the directory of the terminal (not castor working directory)

Under the hood `run` use [`Symfony Process` component](https://symfony.com/doc/current/components/process.html) and AFAIK is not possible to change de current working directory of terminal.

Not tested, but maybe [chdir]( https://www.php.net/manual/fr/function.chdir.php) can do the job but care about the [note](https://www.php.net/manual/fr/function.chdir.php#refsect1-function.chdir-notes)

As alternative you can do something like this to run bash terminal in specific directory : 

`run('env --chdir=/home/theod/Downloads/ bash', tty: true, allowFailure: true);`

But keep in mind that will run under castor and not the terminal directly like a simple `cd` and possibly add some strange behavior (not sure about that)

**Comment by arnolem** [comment]
Thanks a lot.
I tried with `chdir` but that doesn't work either.

Your solution works but indeed, it would be good to know if there is an impact, particularly if we use the script several times, we will find ourselves launching several nested processes?

**Comment by arnolem** [comment]
Unfortunately this workaround will not be satisfactory.

The processes add up and we must exit each bash to exit permanently

![image](https://github.com/jolicode/castor/assets/2263103/3c9ef1be-6238-4bfe-bdca-41b0eb1bf626)

![image](https://github.com/jolicode/castor/assets/2263103/fd88d85c-0ee1-4af4-b764-e41cc37c84c7)

nice try anyway 👍

**Comment by tigitz** [comment]
> /home/user/$ castor goto:projet-a
> Success
> /var/www/projects/projet-a 
> 

Are you trying to make a castor script that would be the equivalent of running `cd` in your bash session? 

Because to execute a PHP script from a Bash terminal that makes your Bash session switch to a specific directory, you'll need to handle the directory switch on the Bash side because a PHP script cannot directly manipulate the environment of the shell that calls it.

In any other cases, what Theo suggested is the way to go when something you run needs to be ran in a specific directory.

Maybe posting the full context of what you're trying to achieve could help.

**Comment by arnolem** [comment]
> Are you trying to make a castor script that would be the equivalent of running cd in your bash session?

yes, this is the feature I need to do 😑
