### ISSUE TITLE
[dev-main] Error : Castor\Console\Command\TaskCommand::__construct(): Argument #2 ($expressionLanguage) must be of type Castor\ExpressionLanguage

### ISSUE THREAD

**Issue by arnolem** [jolicode/castor#456]
I have a problem with the version under development.

```json
{
    "require": {
        "jolicode/castor": "dev-main"
    }
}
```
a simple Task works fine

```php
<?php
use Castor\Attribute\AsTask;

#[AsTask]
function test(): void {}
```

But if I include composer autoload, the code fail

```php
<?php
use Castor\Attribute\AsTask;

require_once __DIR__.'/vendor/autoload.php';

#[AsTask]
function test(): void {}
```

```
08:27:27 WARNING   [castor] User Deprecated: Since castor 0.16: The "Castor\Descriptor\TaskDescriptorCollection" class is deprecated, use "Castor\Descriptor\DescriptorsCollection" instead. ["exception" => ErrorException { …}]

In TaskCommand.php line 39:

Castor\Console\Command\TaskCommand::__construct(): Argument #2 ($expressionLanguage) must be of type Castor\ExpressionLanguage, Castor\EventDispatcher given, called in phar:///usr/local/bin/castor/src/Console/Application.php on line 148
```

**Comment by lyrixx** [comment]
Hello, you are trying to do something that we don't really want to support!

1. Why don't you install castor globally?
1. why do you want to require `vendor/autoload.php` ?

**Comment by lyrixx** [comment]
Anyway, I tried to reproduce your issue, And I'm not able. Everyting works as expected. You you push a full reproducer somewhere?

**Comment by arnolem** [comment]
I think I understood why you are not reproducing the problem.
I installed Castor globally and I run with
```bash
castor test
```

note that if I launch from vendor, I don't have the problem but it is less practical
```bash
vendor/bin/castor test
```

I need to install Castor with Vendor for build commands but that's not really the subject here (as explained in the documentation).

And I need to include autoload because I can install external libraries (to do SFTP).
(Like this example : https://github.com/monsieurbiz/SyliusPluginMaker/blob/master/castor.php)

What am I doing wrong?

**Comment by joelwurtz** [comment]
> And I need to include autoload because I can install external libraries (to do SFTP).
> (Like this example : https://github.com/monsieurbiz/SyliusPluginMaker/blob/master/castor.php)

> What am I doing wrong?

You should use the import system,

You should do : `castor composer require "vendor/lib"` then the autoload will be automatically called by castor and you will have those classes available without needing anything more

**Comment by joelwurtz** [comment]
I do believe your problem is that the castor installed globally and the one required in your composer are not on the same version so you have this error

**Comment by arnolem** [comment]
> > And I need to include autoload because I can install external libraries (to do SFTP).
> > (Like this example : https://github.com/monsieurbiz/SyliusPluginMaker/blob/master/castor.php)
> 
> > What am I doing wrong?
> 
> You should use the import system,
> 
> You should do : `castor composer require "vendor/lib"` then the autoload will be automatically called by castor and you will have those classes available without needing anything more

I think this command is not available yet.

![image](https://github.com/jolicode/castor/assets/2263103/d5addcaa-375d-423e-89f3-d1d43fbf3a71)

**Comment by arnolem** [comment]
> I tested this case too.
> 
> > Can you push a full reproducer somewhere?
> 
> I Still waiting for that

Hello @lyrixx 

You can find, step by step, how to reproduce the problem on a clean Ubuntu 24.04 installation

https://github.com/arnolem/castor-issues-456

**Comment by joelwurtz** [comment]
Your problem is that you have two version of castor that are not the same : 

 * the one installed globally
 * the one installed in your composer
 
What's wrong there is that : 

 * Class from global castor are loaded as needed, until you hit the `require autoload.php`
 * at this point it loads class from the composer version
 
 And then you have a mix between those 2 versions, so indeed this would fail, there is no fix to this, you need to either:
 
 * use the bin castor from your composer deps
 * don't require castor (or autoload)
 * or if you really need that : make sure you have the same version between both castor

**Comment by joelwurtz** [comment]
I'm going to close this, as i don't think we can do much here, feel free to reopen if you think this is an issue from our side
