### ISSUE TITLE
Variadic argument or array

### ISSUE THREAD

**Issue by Spomky** [jolicode/castor#464]
Hello,

I am trying to simplify the way the console commands are called within a Docker env.
But it seems it is not possible.
I tested with a variadic argument, an array or `func_get_args()` without success.

Is it possible or maybe I missed something?

```php
#[AsTask(description: 'Runs a console command.')]
function console(array $args = []): void
{
    run(['docker-compose', 'exec', '-T', 'php', 'bin/console', ...$args]);
}
```

**Comment by lyrixx** [comment]
I'm not sure to understand :/ 

Are you trying to do this https://castor.jolicode.com/getting-started/arguments/?h=array#arguments-without-configuration-nor-validation  ?

Or this https://github.com/jolicode/castor/blob/main/examples/args.php#L20-L21 ?

**Comment by Spomky** [comment]
🤦🏼‍♂️... Indeed it is what I expect. I missed it from the doc.
Many thanks!
