### ISSUE TITLE
Allow an extension / plugin to register variables into context

### ISSUE THREAD

**Issue by joelwurtz** [jolicode/castor#472]
Actually context is created by user, but a plugin can also provide a context.

However there is no possibility to merge them, as an example a custom extension/plugin may propose variable to configure his behavior and allow user to change them if needed, not sure what's best in term of DX, but i think something like this would be nice : 

```php
#[AsListener(ContextCreateEvent::class)]
function update_context(ContextCreateEvent $event) {
    $event->context['value'] ??= 'default';
}
```

I think having context is better, so a plugin can also register environment variables if needed

**Comment by lyrixx** [comment]
Considering the listener, and if the application has N contexts, doest it update all contexts ?

Anyway there is a precedence issue between listener and context creation. Context should be resolved before listener because a listener can use the context 

https://github.com/jolicode/castor/blob/feb54231303bcc8403c612725ab00ffe400bbbe5/src/Kernel.php#L118

**Comment by joelwurtz** [comment]
> Considering the listener, and if the application has N contexts, doest it update all contexts ?

Even if we have N context we generally use one contexts when executing a task, so we will mostly only update one context. 

However if we use another context it should update it as well.
 
> Anyway there is a precedence issue between listener and context creation. Context should be resolved before listener because a listener can use the context

I don't understand this portion, why context should be created before loading listeners, i understand why a context should be created before dispatching an event, but AFAIK listeners can be loaded (not executed) before ?

**Comment by lyrixx** [comment]
> I don't understand this portion, why context should be created before loading listeners, i understand why a context should be created before dispatching an event, but AFAIK listeners can be loaded (not executed) before ?

Hhmmm, you are right!
