### ISSUE TITLE
Just a little list concern

### ISSUE THREAD

**Issue by mark-alexandre** [jolicode/castor#509]
Hi,

I'm approaching to the end of what I can call "a final task manager release" , and I have a vey little concern regarding the list command : is it possible to exclude the 3 included default commands ? And maybe  the 'usage' and 'options' parts too ?

![image](https://github.com/user-attachments/assets/4fcb5944-ca9f-429f-b571-5cac9fb22010)

I'm asking this because my task manager has now a lot of commands, and even if we can display them by namespace, I would be happy to have such an option to clean some unecessary output from the list.

Regards... and thanks again for Castor which is very robust for a little 0.17.1 version. Keep it up.

**Comment by pyrech** [comment]
Hi @mark-alexandre, thanks for your kind words about Castor :yellow_heart: 

About your request, this is not supported at the moment. I don't know if this is feasible easily as these commands and outputs are provided natively by Symfony's Console.

Please let use know if you find something that could eventually be configured easily on our side.

Closing for now, but do not hesitate to reopen with further hints or finds to share :slightly_smiling_face:

**Comment by damienalexandre** [comment]
I didn't try it but it seams you can extend the framework Application and remove the default commands: https://stackoverflow.com/a/61778866/665923

Feel free to suggest a pull request if you find some elegant way to do this in Castor :+1:

**Comment by TheoD02** [comment]
> I didn't try it but it seams you can extend the framework Application and remove the default commands: https://stackoverflow.com/a/61778866/665923
> 
> Feel free to suggest a pull request if you find some elegant way to do this in Castor 👍

Hello, here are working snippet

It's unclear if we want to be provided directly in the Castor source or through a vendor. Let me know 😄 

```php
#[AsListener(event: AfterBootEvent::class)]
function after_boot(AfterBootEvent $event): void
{
    /** @var Application $application */
    $application = $event->application;
    $haystack = context()->environment['EXCLUDED_COMMANDS'] ?? $_SERVER['EXCLUDED_COMMANDS'] ?? $_ENV['EXCLUDED_COMMANDS'] ?? getenv('EXCLUDED_COMMANDS');

    if (!empty($haystack)) {
        $haystack = explode(',', $haystack);
        $haystack = array_map('trim', $haystack);
    } else {
        $haystack = [];
    }

    if (empty($haystack)) {
        return;
    }

    foreach ($application->all() as $command) {
        if (in_array($command->getName(), $haystack, true)) {
            $command->setHidden();
        }
    }
}
```
Can be defined with context, or `.env` but will need to use `load_dot_env()`
```php
#[AsContext]
function root_context(): Context
{
    return new Context(
        environment: [
            'EXCLUDED_COMMANDS' => 'list,completion,help',
        ],
    );
}
```

**Comment by damienalexandre** [comment]
Castor event system is nicely used here! Nice!

That's exactly why it was made, allowing extension and modification like yours :+1: 

I suggest we don't include this in Castor core right now. Let's wait for some more community feedback. If this feature is requested multiple times, we can reconsider.

Thanks for sharing the solution and happy coding :yum: !
