### ISSUE TITLE
404 Error when updating

### ISSUE THREAD

**Issue by gponty** [jolicode/castor#517]
Hi,

 I encountered a 404 error when attempting to update a script using the following command:

`curl "https://castor.jolicode.com/install" | bash -s -- --install-dir /var/tmp`

Error message :

`The requested URL returned error: 404`

Thank you

**Comment by lruozzi9** [comment]
This is caused by #518.

**Comment by gponty** [comment]
Ok, I’ll close this issue then.

Thank you @lruozzi9
