### ISSUE TITLE
Need Documentation

### ISSUE THREAD

**Issue by davidnurdin** [jolicode/castor#524]
Hi guys,

Can you tell if it is possible to repack+compile , but specify a php.ini to microsfx ?

Thanks

**Comment by tigitz** [comment]
While it's possible, this functionality isn't currently supported. We have two potential options to implement it IMO:

We could introduce new options in the Compile command that accept a filepath to an .ini file. This file would be parsed to generate the appropriate `-I key=value` PHP ini SPC build options.

Alternatively, we could accept a list of -I options directly, similar to how SPC does, and simply proxy these to the SPC build command.

If you're interested in seeing this feature implemented, feel free to submit a PR😉

**Comment by lyrixx** [comment]
I opened a PR for this 👍🏼
