### ISSUE TITLE
Make it easier to run multiple tasks sequentially

### ISSUE THREAD

**Issue by ruudk** [jolicode/castor#540]
When migrating from Composer scripts, one feature I really like is that you can define a script that invokes multiple other scripts.

For example:
```json
    "scripts": {
        "dependencies": "vendor/bin/composer-dependency-analyser @additional_args",
        "editorconfig": "vendor/bin/ec",
        "php-cs-fixer": "vendor/bin/php-cs-fixer fix --diff --ansi @additional_args",
        "phpstan": "vendor/bin/phpstan @additional_args",
        "qa": [
            "@composer normalize --diff",
            "@php-cs-fixer",
            "@phpstan",
            "@tests",
            "@dependencies",
            "@editorconfig"
        ],
        "tests": "vendor/bin/phpunit"
    },
```

The `qa` script invokes others.

I know I can write this myself, but I feel a lot of people want something like this, so wouldn't it be an idea to make it easy for people to group certain tasks, and execute them using a single alias?

As soon as 1 task fails, it should stop.

I don't want to use parallel for this, because sometimes that's not possible.

**Comment by lyrixx** [comment]
> I know I can write this myself, but I feel a lot of people want something like this, so wouldn't it be an idea to make it easy for people to group certain tasks, and execute them using a single alias?

I'm not sure to understand how you imagine the solution. Can you share an example?

**Comment by lyrixx** [comment]
I think plain old PHP functions that gather all others call is better here.

```php
function qa()
{
  phpstan();
  cs();
  ...
}
```
