### ISSUE TITLE
Error with PHP 8.4

### ISSUE THREAD

**Issue by COil** [jolicode/castor#546]
When using PHP 8.4, we have the following error ([GitHub Action](https://github.com/strangebuzz/MicroSymfony/actions/runs/11548541066/job/32140113471?pr=105)). 

```
Run castor test

In ErrorHandler.php line 246:
                            
  Unknown error type: 2048  
                            

Error: Process completed with exit code 1.
```

**Comment by lyrixx** [comment]
Could you create a minimal reproducer ?

**Comment by COil** [comment]
https://github.com/strangebuzz/MicroSymfony/pull/105

**Comment by lyrixx** [comment]
This is not really a minimal reproducer :/ 

Anyway, could you try this PR: https://github.com/jolicode/castor/pull/542

**Comment by COil** [comment]
But this this not my code, this is the castor integration on GitHub action thanks to [shivammathur/setup-php](https://github.com/shivammathur/setup-php?tab=readme-ov-file#wrench-tools-support). I haven't installed PHP 8.4 locally yet.

**Comment by lyrixx** [comment]
This not really helpful 😞 
Anyway, could you try the latest release? https://github.com/jolicode/castor/releases/tag/v0.19.0

**Comment by COil** [comment]
Hello, I don't have the right to update [shivammathur/setup-php](https://github.com/shivammathur/setup-php?tab=readme-ov-file#wrench-tools-support).

**Comment by lyrixx** [comment]
1. IIRC, I'm pretty sure it use the latest version by default. The only things you have to do is to restart the job
2. Otherwise, I'm sure it's open source and it accept PR
3. Finally, we also maintain a [github action](https://github.com/castor-php/setup-castor) to install a static castor

**Comment by COil** [comment]
Hello, indeed, It's OK now : https://github.com/strangebuzz/MicroSymfony/actions/runs/11548541066/job/32239890217?pr=105

Thanks!
