### ISSUE TITLE
[Feature request] Add a function to execute a vendored binary/script (aka `composer exec`)

### ISSUE THREAD

**Issue by cedx** [jolicode/castor#547]
If I want to run a command from a vendored package (think: `phpunit`, `phpstan`, etc.), I have to prefix the command line by `php vendor/bin/`... which is a bit cumbersome.

```php
// In the Castor documentation...
exit_code(["php", "vendor/bin/phpunit", "--filter", "MyTest"]);

// A better alternative for my use cases...
exit_code(["composer", "exec", "--", "phpunit", "--filter", "MyTest"]);
```

So I added this helper to **all** my projects:

```php
// Executes a vendored binary/script.
function _exec(string $command, string ...$args): int {
    return exit_code(["composer", "exec", "--", $command, ...$args]);
}

// Then use it in a task...
return _exec("phpunit", "--filter", "MyTest");
```

It would be cool if this feature was built in.

**Comment by joelwurtz** [comment]
Not quite exactly what you want, but you can use the `run_phar` function that should use the same php that was used for castor to run a php script, it even work on static castor binary (so it works everywhere)

**Comment by joelwurtz** [comment]
And for this issue, i don't think we should provide default like this, we already handle a lot of commands, writing those kind of helper works really well for end user i don't think we want to handle all use cases.

**Comment by cedx** [comment]
OK! Not a big deal to add these 3 lines to each project.
