### ISSUE TITLE
Reconsider deprecation of `$environment` parameter in `run()`

### ISSUE THREAD

**Issue by tigitz** [jolicode/castor#563]
Hello everyone,

I've reached a stage in my Castor usage where I need to refactor and centralize the logic that builds my commands. After some consideration, I've settled on the following architecture:

**tools/castor/src/docker.php**
```php
/**
 * Build a docker-compose command.
 *
 * @param array<int|string|\Stringable>|string $command
 * @param array<string, int|string|\Stringable> $environment
 *
 * @return array{command: list<int|string|\Stringable>, environment: array<string, int|string|\Stringable>}
 */
function dcp(string|array $command, array $environment = []): array
{
    $command = \is_array($command) ? $command : explode(' ', $command);

    return ['command' => ['docker', 'compose', ...$command], 'environment' => $environment];
}

/**
 * @param array<string, int|string|\Stringable> $environment
 *
 * @return array{command: list<int|string|\Stringable>, environment: array<string, int|string|\Stringable>}
 */
function dcp_start(bool $forceRecreate = false, array $environment = []): array
{
    $args = 'up -d --remove-orphans';
    if ($forceRecreate) {
        $args .= ' --force-recreate';
    }

    return dcp($args, $environment);
}

/**
 * @return array{command: list<int|string|\Stringable>, environment: array<string, int|string|\Stringable>}
 */
function dcp_down(): array
{
    return dcp('down');
}
```

**castor.php**
```php
require_once __DIR__ . '/tools/castor/src/docker.php';

#[AsTask(name: 'start', description: 'Start the Docker containers')]
function task_start(): void
{
    run(...dcp_start());
}

#[AsTask(name: 'restart', description: 'Start the Docker containers, ensuring all necessary services are running, and install PHP dependencies using Composer.')]
function task_restart(): void
{
    run(...dcp_start(true));
}

#[AsTask(name: 'down', description: 'Stop and remove all running Docker containers, cleaning up the environment.', aliases: ['stop'])]
function task_down(): void
{
    run(...dcp_down());
}
```

However, this implementation throws a deprecation notice since it relies on the now-deprecated `array $environment` parameter in `run()`, requiring the use of `run(context: context()->withEnvironment())`. This means I can no longer do a simple `run(...['command' => 'my-command', 'environment' => ['FOO' => 'bar']])`.

In my setup, returning both the command and the associated environment variables feels more intuitive, as it mirrors the way we typically structure commands in the command line (e.g., `FOO=bar my-command-line`). Forcing part of my command into `run(command: 'my-command-line')` and the other into a less readable `run(context: context()->withEnvironment(['FOO' => 'bar']))` feels somewhat counterintuitive and rigid.

Would it be possible to reconsider the deprecation and retain the environment parameter as a DX improvement? This approach would essentially act as a proxy to `context()->withEnvironment()` without much downside IMO.

**Comment by lyrixx** [comment]
What about adding your own run command, that does what our run command require?

**Comment by tigitz** [comment]
This is indeed what I did in the meantime. Here’s the workaround I implemented to bypass the deprecation notices for now:

```php
namespace app {
    /**
     * @param string|array<string|\Stringable|int>}|\Castor\CommandBuilder\CommandBuilderInterface $command
     * @param array<string, string|\Stringable|int>}|null $environment
     * @param callable(string, string, \Symfony\Component\Process\Process): void|null $callback
     */
    function run(string|array|CommandBuilderInterface $command, ?array $environment = null, ?string $workingDirectory = null, ?bool $tty = null, ?bool $pty = null, ?float $timeout = null, ?bool $quiet = null, ?bool $allowFailure = null, ?bool $notify = null, ?callable $callback = null, ?Context $context = null, ?string $path = null): Process
    {
        return \Castor\run(
            command: $command,
            workingDirectory: $workingDirectory,
            tty: $tty,
            pty: $pty,
            timeout: $timeout,
            quiet: $quiet,
            allowFailure: $allowFailure,
            notify: $notify,
            callback: $callback,
            context: $context?->withEnvironment($environment ?? []) ?? \Castor\context()->withEnvironment($environment ?? []),
            path: $path
        );
    }

    /**
     * @param string|array<string|\Stringable|int>} $command
     * @param array<string, string|\Stringable|int>}|null $environment
     */
    function capture(string|array $command, ?array $environment = null, ?string $workingDirectory = null, ?float $timeout = null, ?bool $allowFailure = null, ?string $onFailure = null, ?Context $context = null, ?string $path = null): string
    {
        return \Castor\capture(
            command: $command,
            workingDirectory: $workingDirectory,
            timeout: $timeout,
            allowFailure: $allowFailure,
            onFailure: $onFailure,
            context: $context?->withEnvironment($environment ?? []) ?? \Castor\context()->withEnvironment($environment ?? []),
            path: $path
        );
    }
    /**
     * @param string|array<string|\Stringable|int>} $command
     * @param array<string, string|\Stringable|int>}|null $environment
     */
    function exit_code(string|array $command, ?array $environment = null, ?string $workingDirectory = null, ?float $timeout = null, ?bool $quiet = null, ?Context $context = null, ?string $path = null): int
    {
        return \Castor\exit_code(
            command: $command,
            workingDirectory: $workingDirectory,
            timeout: $timeout,
            quiet: $quiet,
            context: $context?->withEnvironment($environment ?? []) ?? \Castor\context()->withEnvironment($environment ?? []),
            path: $path
        );
    }
}
}
````

That said this approach does introduce additional maintenance overhead, especially considering Castor’s fast-paced development and lack of a stable version. I fear each update could break my 

I suspect other users particularly newcomers to Castor may face similar challenges so addressing this at the core level could enhance usability and make Castor more approachable IMO and that's why I created this issue. But it's only my opinion 😉

**Comment by lyrixx** [comment]
Weel, we removed all argument because of maintenance. Now it's simpler, there is not a ton of argument to handle. Future addition will be easy (only in the context)

I'm sorry for the deprecation, but castor is quite stable now. I think we won't change the signature anymore.

---

Anyway, did you see https://castor.jolicode.com/going-further/extending-castor/command-builder/ ? 

I think you could leverage this to abstract your docker layer.

---


Finally, Why don't you do:
```php
function task_start(): void
{
    $start = dcp_start();
    run($start['command'], context: context()->withEnvironment($start['environment]));
}

**Comment by tigitz** [comment]
Thank you for pointing that out! The command builder approach is indeed exactly what I need for my advanced use case and provides the clarity and readability of `run(dcp())` I want when working with the task file. Not sure how I've missed it 🤦 Appreciate the guidance!

**Comment by tigitz** [comment]
> You can already do that with the command builder ?
> 
> Does https://castor.jolicode.com/going-further/extending-castor/command-builder/#forcing-the-context-of-the-command-builder (the `ContextUpdateInterface` interface) solve your problem ?

I guess it could work yes, thanks for the tip I've missed it.

**Comment by pyrech** [comment]
I think the issue can be closed now 🙂 Do not hesitate to reopen if you still miss something. Thanks for the discussion 👍
